### ISSUE TITLE
Single $ signs no longer working?

### ISSUE THREAD

**Issue by daixtrose** [hbshim/mediawiki-mathjax#2]
We recently upgraded to mediawiki-1.28 and use the MathJax Plugin as described [here](https://www.mediawiki.org/wiki/Extension:MathJax). 

Thanks for the great job of maintaining this system. Our old mediawiki 1.21.2 together with Mathjax allowed the shortcut notation

```$x = \frac{1}{2}$```

but this seems to no longer work. In contrast 

```\[ x = \frac{1}{2} \]``` 

works like a charm.

Is there any technical limitation or reason for this change and is there an easy way to fix this? 

```php
static function ReplaceByMarkers(Parser &$parser, &$text )
    {
        // this line added
        $text = preg_replace_callback('/(\$)(.*?)(\$)/s', 'MathJax_Parser::Marker',$text);
```
does not work as hoped for.

**Comment by jbalint** [comment]
It's working well for me on MediaWiki 1.28.1 and PHP 7.1.3. Perhaps you can check what HTML is rendered. I'm getting the literal text $x$ in the rendered page before MathJax renders it.

**Comment by daixtrose** [comment]
@jbalint we cannot fix it this way: We upgraded to MediaWiki 1.28.2 and already had PHP 7.1.3 running. Same result:

![image](https://cloud.githubusercontent.com/assets/5588692/25627680/b2d9e56c-2f63-11e7-9a1f-ce322611862b.png)

How can i check which HTML is rendered?

**Comment by daixtrose** [comment]
MathJax was not touched by us in this regard and reads

```
inlineMath: [ ['$','$'], ["\\(","\\)"] ],
displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
```

Interesting enough 

```
\(y = \frac{1}{2}\)
```

yields the expected result, so the dollar sign has some issue.

**Comment by daixtrose** [comment]
It seems we had a typo in the MediaWiki config which hindered the inclusion of ```local/mwmathJaxConfig```. Sorry for stealing your time.
