### ISSUE TITLE
Formula references no longer functional

### ISSUE THREAD

**Issue by daixtrose** [hbshim/mediawiki-mathjax#3]
MediaWiki 1.21.2 together with an older version of Mathjax supported formula references:

```
<math>
\begin{align}
  \label{def:Wns}
  W_n (s)
  &:= 
  \int_{[0, 1]^n} 
    \left| \sum_{k = 1}^n \mathrm{e}^{2 \pi \mathrm{i} \, x_k} \right|^s \mathrm{d}\boldsymbol{x}
\end{align}
</math>

the integral \eqref{def:Wns} expresses the <math>s</math>
```` 

yielded 

![image](https://cloud.githubusercontent.com/assets/5588692/25533579/5fab86a0-2c31-11e7-9297-afb76252bd7b.png)

but this feature seems to no longer work.

**Comment by jbalint** [comment]
Is this something that MathJax does? This extension is quite simple and relies on MathJax to do the real work.

**Comment by daixtrose** [comment]
This is a feature that used to work, so please consider this as a regression.

**Comment by daixtrose** [comment]
It seems we had a typo in the MediaWiki config which hindered the inclusion of ```local/mwmathJaxConfig```. Sorry for stealing your time.
